### ISSUE TITLE
Streams vs file reading

### ISSUE THREAD

**Issue by fabiantheblind** [frntl/frontal#45]
Should we use streams instead of just reading files?

> This document covers the basics of how to write node.js programs with streams.
> https://github.com/substack/stream-handbook/blob/master/readme.markdown

**Comment by sebastian-meier** [comment]
What would be the advantage?

Because i am also quite happy that there is a filereadSYNC so i don't need
to create ridiculously nested loading functions to make sure x is loaded
before y...


Fabian Morón Zirfas <notifications@github.com> schrieb am Do., 19. Nov.
2015 um 07:28 Uhr:

> Assigned #45 <https://github.com/frntl/frontal/issues/45> to
> @sebastian-meier <https://github.com/sebastian-meier>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frntl/frontal/issues/45#event-468823012>.
>
-- 

Sebastian Meier
Human-Centered Visualization Research
_______________

contact@sebastianmeier.eu
www.sebastianmeier.eu
+491751506707
@seb_meier

**Comment by fabiantheblind** [comment]
Hm. Because it would be faster?

**Comment by fabiantheblind** [comment]
and more nodejs-esque

**Comment by sebastian-meier** [comment]
lets add it as a future todo, as this will require quite some code rewriting

Fabian Morón Zirfas <notifications@github.com> schrieb am Do., 19. Nov.
2015 um 12:45 Uhr:

> and more nodejs-esque
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frntl/frontal/issues/45#issuecomment-158032515>.
>
-- 

Sebastian Meier
Human-Centered Visualization Research
_______________

contact@sebastianmeier.eu
www.sebastianmeier.eu
+491751506707
@seb_meier

**Comment by fabiantheblind** [comment]
aight.
